apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  targetNamespace: cnpg-system
  releaseName: cloudnative-pg
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.20.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  interval: 10m
  install:
    createNamespace: true
