apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres-cluster-metrics
  namespace: default
  labels:
    prometheus: kube-prometheus  # Important: This label helps Prometheus find it
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: postgres-cluster
  podMetricsEndpoints:
  - port: metrics
    interval: 30s
