apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-cluster-metrics
  namespace: default
  labels:
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: postgres-cluster
      cnpg.io/podRole: instance
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
