apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: phoenix-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh", "-c"]
        args:
          - |
            mkdir -p /app/priv/static
            cp -r /public/. /app/priv/static/ || true
            export MIX_ENV=dev
            exec /app/bin/hello start
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: http
        env:
        - name: URL_HOST
          value: "localhost"
        - name: URL_SCHEME
          value: "http"
        - name: URL_PORT
          value: "8000"
        - name: PORT
          value: "8000"
        - name: SECRET_KEY_BASE
          value: "really-long-secret-key-base-at-least-64-characters-for-production-phoenix-app-use"
        - name: POSTGRES_USER
          value: "phoenix_user"
        - name: POSTGRES_PASSWORD
          value: "phoenix_password123"
        - name: POSTGRES_HOST
          value: "postgres-cluster-rw"
        - name: POSTGRES_DB
          value: "phoenix_app"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_POOL
          value: "10"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
