replicaCount: 2

image:
  repository: jasaulakh/phoenix-app
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8000
  targetPort: 8000
  nodePort: 30080

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  PORT: "8000"
  MIX_ENV: "prod"
  PHX_HOST: "localhost"
  PHX_SERVER: "true"
  
database:
  host: postgres-cluster.default.svc.cluster.local
  port: 5432
  name: phoenix_app
  username: phoenix_user
  password: phoenix_password123

secret:
  secretKeyBase: "really-long-secret-key-base-at-least-64-characters-for-production-phoenix-app-use"
