apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnativepg
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/cloudnativepg
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
